version: '3.7'

services:
  server:
    image: clojure
    volumes:
      - ~/.bash_history:/.bash_history
      - ./services/app:/app
      - repo:/repo
    working_dir: /app
  jclient:
    image: maven
    volumes:
      - ~/.bash_history:/.bash_history"
      - ./services/jclient:/app
      - repo:/repo
    working_dir: /app

volumes:
  repo:
