version: '3.7'

services:
  app:
    image: clojure
    volumes:
      - ~/.bash_history:/.bash_history
      - ./services/app:/app
      - repo:/repo
    working_dir: /app
  client:
    image: maven
    volumes:
      - ~/.bash_history:/.bash_history"
      - ./services/client:/app
      - repo:/repo
    working_dir: /app

volumes:
  repo:
